language: c
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgmp-dev libssl-dev check autoconf automake m4
script: autoreconf -iv && ./configure && make && make check
compiler:
  - clang
  - gcc
